/**
 * Test PDF generation locally — saves the PDF to disk without sending email.
 * Usage: node test-pdf.mjs
 */

import { writeFileSync } from 'fs';

const testData = {
  title: 'Mr',
  firstName: 'Test',
  middleName: 'James',
  lastName: 'Applicant',
  dob: '1990-01-15',
  gender: 'Male',
  nationality: 'British',
  ethnicity: 'White British',
  religion: 'None',
  sexualOrientation: 'Prefer not to say',
  niNumber: 'AB123456C',
  nmcPin: 'NMC123',
  rcnNumber: 'RCN456',
  hpcNumber: '',
  band: 'Band 5',
  mobileNo: '07700900000',
  homePhone: '02034415474',
  email: 'test@example.com',
  streetAddress: '52 Upper Street',
  city: 'London',
  county: 'Greater London',
  postcode: 'N1 0QH',
  role: 'Care Worker',
  permittedToWork: 'Yes',
  canProvideEvidence: 'Yes',
  rightToWorkProof: 'Passport',
  visaType: '',
  permitDocNumber: '',
  passportNo: 'GB12345678',
  visaExpiryDate: '',
  hasFullLicence: 'Yes',
  drivingLicenceNo: 'APPLI901015TF9PQ',
  hasCarForWork: 'Yes',
  drivingBan: 'No',
  vehicleDocsUpToDate: 'Yes',
  travelToWork: 'Own car',
  availability: ['Monday', 'Tuesday', 'Wednesday'],
  workingTimeDirective: 'No — I do not wish to work more than 48 hours per week',
  nokTitle: 'Mrs',
  nokFirstName: 'Jane',
  nokLastName: 'Applicant',
  nokRelationship: 'Spouse',
  nokMobile: '07700900001',
  nokHomePhone: '02034415475',
  nokEmail: 'jane@example.com',
  nokStreet: '52 Upper Street',
  nokCity: 'London',
  nokCounty: 'Greater London',
  nokPostcode: 'N1 0QH',
  ref1FirstName: 'Dr',
  ref1LastName: 'Smith',
  ref1Relationship: 'Previous Employer',
  ref1Email: 'drsmith@example.com',
  ref1Phone: '07700900002',
  ref1Street: '10 Medical Road',
  ref1City: 'London',
  ref1County: 'Greater London',
  ref1Postcode: 'W1A 1AA',
  ref2FirstName: 'Ms',
  ref2LastName: 'Jones',
  ref2Relationship: 'Character Reference',
  ref2Email: 'msjones@example.com',
  ref2Phone: '07700900003',
  ref2Street: '20 Care Lane',
  ref2City: 'London',
  ref2County: 'Greater London',
  ref2Postcode: 'E1 6RF',
  completedMandatoryTraining: 'Yes',
  mandatoryTraining: ['Manual Handling', 'First Aid', 'Fire Safety'],
  mandatoryTrainingDates: '2024-03-01',
  completedOtherTraining: 'Yes',
  otherTraining: ['Dementia Awareness'],
  otherTrainingDates: '2024-01-15',
  hasDbs: 'Yes',
  dbsClear: 'Yes',
  dbsIssueDate: '2023-06-01',
  dbsDisclosureNumber: 'DBS123456789',
  longTermIllness: 'No',
  sickLeaveBackNeck: 'No',
  backNeckInjury: '',
  contactContagious: 'No',
  communicableDisease: 'No',
  activemedicalAttention: 'No',
  healthDetails: '',
  registeredDisabled: 'No',
  illnessDaysAbsent: '2',
  absenceReasons: 'Common cold',
  illnessAffectsWork: 'No',
  illnessCausedByWork: 'No',
  awaitingTreatment: 'No',
  needsAdjustments: 'No',
  medicalAdditional: '',
  livedInUK5Years: 'Yes',
  countriesLived: '',
  bcgVaccination: 'Yes',
  bcgDate: '2005-09-01',
  persistentCough: 'No',
  unexplainedWeightLoss: 'No',
  unexplainedFever: 'No',
  hadTB: 'No',
  tbAdditional: '',
  hadChickenPox: 'Yes',
  chickenPoxDate: '1995-04-01',
  tripleVaccination: 'Yes',
  polio: 'Yes',
  tetanus: 'Yes',
  hepatitisB: 'Yes',
  hepatitisBDetails: 'Fully vaccinated',
  exposureProneProcedures: 'No',
  criminalConviction: 'No',
  cautionedOrWarned: 'No',
  criminalDetails: '',
  rightToWorkDocument: 'Passport',
  declarationFullName: 'Test Applicant',
  declarationDate: new Date().toISOString().split('T')[0],
  privacyConsent: true,
  dbsDeclarationConfirm: true,
  healthDeclarationConfirm: true,
};

const boundary = '----FormBoundary' + Math.random().toString(36).slice(2);
const body = `--${boundary}\r\nContent-Disposition: form-data; name="data"\r\n\r\n${JSON.stringify(testData)}\r\n--${boundary}--\r\n`;

// Call a dedicated PDF-only test endpoint
const res = await fetch('http://localhost:3000/api/test-pdf', {
  method: 'POST',
  headers: { 'Content-Type': `multipart/form-data; boundary=${boundary}` },
  body,
});

if (res.ok) {
  const buffer = Buffer.from(await res.arrayBuffer());
  writeFileSync('test-output.pdf', buffer);
  console.log('✅ PDF saved to test-output.pdf — open it to verify all fields are present.');
} else {
  const json = await res.json().catch(() => ({}));
  console.error('❌ Failed:', json.message || res.status);
}
